# Generated by Django 4.2.5 on 2023-09-28 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='Please Enter Your Full Name', max_length=50)),
                ('subject', models.CharField(default='Please Enter The Subject', max_length=255)),
                ('message', models.TextField(default='Please Enter Your Feedback')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
